apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: etcd-anycast-healthcheck
  namespace: kubermesh
spec:
  template:
    metadata:
      labels:
        name: etcd-anycast-healthcheck
    spec:
      hostNetwork: true
      containers:
        - name: healthcheck
          image: kubermesh/minimal-anycast-healthcheck
          resources:
            requests:
              cpu: 0.15
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: DEVICE
              value: dummy0
            - name: IP
              value: fd65:7b9c:569:680:98eb:c508:ea6b:b0b2
            - name: PORT
              value: "2379"
