apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-scheduler
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: kube-scheduler
    spec:
      containers:
      - name: kube-scheduler
        image: quay.mirror.kubermesh:5001/coreos/hyperkube:v1.5.1_coreos.0
        imagePullPolicy: Always
        command:
        - ./hyperkube
        - scheduler
        - --leader-elect=true
        resources:
          limits:
            cpu: 100m
            memory: 100Mi