apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-api-anycast-healthcheck
  namespace: kubermesh
spec:
  template:
    metadata:
      labels:
        name: kube-api-anycast-healthcheck
    spec:
      hostNetwork: true
      containers:
        - name: healthcheck
          image: hub.mirror.kubermesh:5000/kubermesh/minimal-anycast-healthcheck
          resources:
            requests:
              cpu: 0.01
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: DEVICE
              value: dummy0
            - name: IP
              value: fd65:7b9c:569:680:98eb:c508:eb8c:1b80
            - name: PORT
              value: "443"
