apiVersion: "extensions/v1beta1"
kind: DaemonSet
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        k8s-app: kube-proxy
    spec:
      hostNetwork: true
      containers:
      - name: kube-proxy
        image: quay.mirror.kubermesh:5001/coreos/hyperkube:v1.5.1_coreos.0
        imagePullPolicy: Always
        command:
        - /hyperkube
        - proxy
        - --master=https://[fd65:7b9c:569:680:98eb:c508:eb8c:1b80]:443
        - --kubeconfig=/etc/kubernetes/kubeconfig
        - --proxy-mode=iptables
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ssl-certs-host
          readOnly: true
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
          readOnly: true
      volumes:
      - hostPath:
          path: /usr/share/ca-certificates
        name: ssl-certs-host
      - name: etc-kubernetes
        hostPath:
          path: /etc/kubernetes
